GNN_hidden_dim: 32
K: 3
act_GNN_hidden_dim: 32
action_masking: true
activation_function: relu
batch_size: 128
config_file: PST_V2G_ProfixMax_25.yaml
dataset_path: PST_V2G_ProfixMax_25_real_optimal_25_400.pkl.gz
dropout: 0.1
embed_dim: 128
env: baseline
eval_replay_path: ./eval_replays/train/PST_V2G_ProfixMax_25_real_optimal_25_30/
feature_dim: 8
gnn_type: GCN
learning_rate: 0.0001
max_iters: 100
mode: normal
n_head: 1
n_layer: 32
name: baseline400
num_act_gcn_layers: 3
num_eval_episodes: 3
num_gcn_layers: 3
num_steps_per_iter: 1000
pct_traj: 1.0
resume_model: null
seed: 42
warmup_steps: 10000
weight_decay: 0.0001
