"""
evaluate_model.py
=================
对训练好的 GNN-DT 模型进行独立评估。

用法：
  python evaluate_model.py --model_path ./saved_models/baseline/model.best --eval_replay_path ./eval_replays/low_stress_replays/ --output_dir ./eval_results/baseline_low/

输出：
  output_dir/
  ├── per_episode_stats.csv      # 每条轨迹的详细指标
  ├── summary.csv                # 汇总表 (mean ± std)
  ├── summary.json               # 机器可读的汇总
  └── (plots are generated by compare_models.py)
"""

import os
import sys
import time
import argparse
import json
import csv
import numpy as np
import torch
import yaml
import pickle
import tqdm

from DT.models.gnn_decision_transformer import GNN_DecisionTransformer
from ev2gym.models.ev2gym_env import EV2Gym
from utils import PST_V2G_ProfitMax_reward, PST_V2G_ProfitMax_state


def load_model(model_path, config, device, vars_override=None):
    """从 checkpoint 加载 GNN-DT 模型。"""

    # 尝试从同目录下的 vars.yaml 读取训练时的超参数
    model_dir = os.path.dirname(model_path)
    vars_path = os.path.join(model_dir, "vars.yaml")

    if os.path.exists(vars_path):
        with open(vars_path, 'r') as f:
            v = yaml.safe_load(f)
    else:
        # 使用默认值
        v = {}

    if vars_override:
        v.update(vars_override)

    # 与 train_DT.py 保持一致的默认值
    state_dim = v.get('state_dim', 1500)
    act_dim = v.get('act_dim', 250)

    model = GNN_DecisionTransformer(
        state_dim=state_dim,
        act_dim=act_dim,
        max_length=v.get('K', 3),
        max_ep_len=config.get('simulation_length', 96),
        hidden_size=v.get('embed_dim', 128),
        n_layer=v.get('n_layer', 3),
        n_head=v.get('n_head', 1),
        n_inner=4 * v.get('embed_dim', 128),
        activation_function=v.get('activation_function', 'relu'),
        n_positions=1024,
        resid_pdrop=v.get('dropout', 0.1),
        attn_pdrop=v.get('dropout', 0.1),
        action_tanh=True,
        action_masking=v.get('action_masking', True),
        fx_node_sizes={'ev': 5, 'cs': 4, 'tr': 2, 'env': 6},
        feature_dim=v.get('feature_dim', 8),
        GNN_hidden_dim=v.get('GNN_hidden_dim', 32),
        num_gcn_layers=v.get('num_gcn_layers', 3),
        config=config,
        device=device,
    )

    model.load_state_dict(torch.load(model_path, map_location=device))
    model.to(device)
    model.eval()
    print(f"Loaded model from {model_path}")
    return model, state_dim, act_dim


def evaluate_single_episode(env, model, state_dim, act_dim, config, device,
                            max_ep_len=96, scale=1.0):
    """对单个 replay 环境跑一次完整 episode，返回 stats dict + 用时。"""

    state, _ = env.reset()

    # padding
    padded_state = np.zeros(state_dim)
    padded_state[:min(len(state), state_dim)] = state[:state_dim]

    states = torch.from_numpy(padded_state).reshape(
        1, state_dim).to(device=device, dtype=torch.float32)
    actions = torch.zeros((0, act_dim), device=device, dtype=torch.float32)
    actions_mask = torch.zeros((1, act_dim), device=device, dtype=torch.float32)
    rewards = torch.zeros(0, device=device, dtype=torch.float32)

    # 不做 state 归一化（与 evaluate_episode_rtg 保持一致）
    state_mean = torch.zeros(state_dim, device=device)
    state_std = torch.ones(state_dim, device=device)

    target_return = torch.tensor(0.0, device=device, dtype=torch.float32).reshape(1, 1)
    timesteps = torch.tensor(0, device=device, dtype=torch.long).reshape(1, 1)

    episode_return = 0.0
    step_times = []

    for t in range(max_ep_len):
        actions = torch.cat([actions, torch.zeros((1, act_dim), device=device)], dim=0)
        rewards = torch.cat([rewards, torch.zeros(1, device=device)])

        t_start = time.perf_counter()

        action = model.get_action(
            (states.to(dtype=torch.float32) - state_mean) / state_std,
            actions.to(dtype=torch.float32),
            rewards.to(dtype=torch.float32),
            target_return.to(dtype=torch.float32),
            timesteps.to(dtype=torch.long),
            actions_mask.to(dtype=torch.float32),
            config=env.config,
        )

        t_end = time.perf_counter()
        step_times.append(t_end - t_start)

        actions[-1] = action
        action_to_env = action.detach().cpu().numpy()[:env.action_space.shape[0]]

        state, reward, done, truncated, stats = env.step(action_to_env)

        # action mask padding
        action_mask = np.zeros(act_dim)
        orig_am = stats['action_mask']
        action_mask[:len(orig_am)] = orig_am
        actions_mask = torch.cat([
            actions_mask,
            torch.from_numpy(action_mask).to(device=device).reshape(1, act_dim)
        ], dim=0)

        # state padding
        padded_state = np.zeros(state_dim)
        padded_state[:min(len(state), state_dim)] = state[:state_dim]
        states = torch.cat([
            states,
            torch.from_numpy(padded_state).to(device=device).reshape(1, state_dim)
        ], dim=0)

        rewards[-1] = reward
        pred_return = target_return[0, -1] - (reward / scale)
        target_return = torch.cat([target_return, pred_return.reshape(1, 1)], dim=1)
        timesteps = torch.cat([
            timesteps,
            torch.ones((1, 1), device=device, dtype=torch.long) * (t + 1)
        ], dim=1)

        episode_return += reward

        if done:
            break

    stats['exec_time_per_step'] = np.mean(step_times)
    return stats


def run_evaluation(model_path, eval_replay_path, config_path, output_dir,
                   max_episodes=None, device_str='auto'):
    """主评估流程。"""

    device = torch.device("cuda" if (device_str == 'auto' and torch.cuda.is_available())
                          else device_str if device_str != 'auto' else "cpu")
    print(f"Device: {device}")

    config = yaml.safe_load(open(config_path, 'r'))
    max_ep_len = config.get('simulation_length', 96)

    reward_function = PST_V2G_ProfitMax_reward
    state_function = PST_V2G_ProfitMax_state

    # 加载模型
    model, state_dim, act_dim = load_model(model_path, config, device)

    # 加载 replay 文件
    replay_files = sorted([f for f in os.listdir(eval_replay_path) if f.endswith('.pkl')])
    if max_episodes:
        replay_files = replay_files[:max_episodes]
    print(f"Found {len(replay_files)} replay files in {eval_replay_path}")

    # 逐条评估
    all_stats = []
    for i, rf in enumerate(tqdm.tqdm(replay_files, desc="Evaluating")):
        replay_path = os.path.join(eval_replay_path, rf)
        env = EV2Gym(
            config_file=config_path,
            load_from_replay_path=replay_path,
            state_function=state_function,
            reward_function=reward_function,
        )

        with torch.no_grad():
            stats = evaluate_single_episode(
                env, model, state_dim, act_dim, config, device,
                max_ep_len=max_ep_len,
            )

        stats['replay_file'] = rf
        stats['episode_idx'] = i
        all_stats.append(stats)
        env.close()

    # ==================== 保存结果 ====================
    os.makedirs(output_dir, exist_ok=True)

    # ---- 核心指标 keys ----
    metric_keys = [
        'total_reward',
        'total_profits',
        'total_energy_charged',
        'total_energy_discharged',
        'average_user_satisfaction',
        'min_user_satisfaction',
        'power_tracker_violation',
        'tracking_error',
        'energy_tracking_error',
        'total_transformer_overload',
        'battery_degradation',
        'exec_time_per_step',
    ]
    # optimal 对照 keys
    opt_keys = [k for k in all_stats[0].keys() if k.startswith('opt_')]

    # ---- per-episode CSV ----
    per_ep_path = os.path.join(output_dir, "per_episode_stats.csv")
    all_csv_keys = ['episode_idx', 'replay_file'] + metric_keys + opt_keys
    with open(per_ep_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=all_csv_keys, extrasaction='ignore')
        writer.writeheader()
        for s in all_stats:
            writer.writerow(s)
    print(f"Saved per-episode stats to {per_ep_path}")

    # ---- summary (mean ± std) ----
    summary = {}
    for key in metric_keys + opt_keys:
        vals = [s.get(key, np.nan) for s in all_stats]
        vals = [v for v in vals if v is not None and not (isinstance(v, float) and np.isnan(v))]
        if vals:
            summary[key] = {
                'mean': float(np.mean(vals)),
                'std': float(np.std(vals)),
                'min': float(np.min(vals)),
                'max': float(np.max(vals)),
            }

    # optimality gap
    if 'total_reward' in summary and 'opt_total_reward' in summary:
        model_r = summary['total_reward']['mean']
        opt_r = summary['opt_total_reward']['mean']
        if abs(opt_r) > 1e-9:
            summary['optimality_gap_pct'] = {
                'mean': float((model_r - opt_r) / abs(opt_r) * 100),
            }

    summary_path = os.path.join(output_dir, "summary.json")
    with open(summary_path, 'w', encoding='utf-8') as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)
    print(f"Saved summary to {summary_path}")

    # ---- 人类可读的 summary CSV（论文 Table 格式）----
    table_path = os.path.join(output_dir, "summary_table.csv")
    # 映射到论文 Table 8 的列名
    display_map = [
        ("Reward [-]",             "total_reward"),
        ("Energy Charged [kWh]",   "total_energy_charged"),
        ("Energy Discharged [kWh]","total_energy_discharged"),
        ("User Satisfaction [%]",  "average_user_satisfaction"),
        ("Power Violation [kW]",   "power_tracker_violation"),
        ("Costs [€]",             "total_profits"),
        ("Tracking Error",         "tracking_error"),
        ("Exec. Time [sec/step]",  "exec_time_per_step"),
    ]
    with open(table_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(["Metric", "Mean", "Std", "Min", "Max"])
        for display_name, key in display_map:
            if key in summary:
                s = summary[key]
                writer.writerow([
                    display_name,
                    f"{s['mean']:.4f}",
                    f"{s['std']:.4f}",
                    f"{s['min']:.4f}",
                    f"{s['max']:.4f}",
                ])
        # optimality gap
        if 'optimality_gap_pct' in summary:
            writer.writerow([
                "Optimality Gap [%]",
                f"{summary['optimality_gap_pct']['mean']:.2f}",
                "", "", "",
            ])
    print(f"Saved summary table to {table_path}")

    # ---- 打印汇总 ----
    print("\n" + "=" * 60)
    print("EVALUATION SUMMARY")
    print("=" * 60)
    for display_name, key in display_map:
        if key in summary:
            s = summary[key]
            print(f"  {display_name:30s}  {s['mean']:>10.4f} ± {s['std']:.4f}")
    if 'optimality_gap_pct' in summary:
        print(f"  {'Optimality Gap [%]':30s}  {summary['optimality_gap_pct']['mean']:>10.2f}%")
    print("=" * 60)

    return summary, all_stats


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Evaluate a trained GNN-DT model")
    parser.add_argument('--model_path', type=str, required=True,
                        help='Path to model checkpoint, e.g. ./saved_models/xxx/model.best')
    parser.add_argument('--eval_replay_path', type=str, required=True,
                        help='Directory containing replay .pkl files')
    parser.add_argument('--config_file', type=str,
                        default='./config_files/PST_V2G_ProfixMax_25.yaml')
    parser.add_argument('--output_dir', type=str, default='./eval_results/default/')
    parser.add_argument('--max_episodes', type=int, default=None,
                        help='Max number of episodes to evaluate (None = all)')
    parser.add_argument('--device', type=str, default='auto',
                        help='Device: auto, cpu, or cuda')
    args = parser.parse_args()

    run_evaluation(
        model_path=args.model_path,
        eval_replay_path=args.eval_replay_path,
        config_path=args.config_file,
        output_dir=args.output_dir,
        max_episodes=args.max_episodes,
        device_str=args.device,
    )
